package org.moreno.views.tabs;

import com.intellij.uiDesigner.core.GridLayoutManager;
import org.moreno.components.TabPane;
import org.moreno.models.Product;

import javax.swing.*;
import java.awt.*;

public class TabRecords {
    private TabPane contentPane;
    private Product product;

    public TabRecords(Product product) {
        this.product = product;
        initComponents();
    }

    private void initComponents() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
